// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// InternalError defines model for InternalError.
type InternalError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// SigninRequest defines model for SigninRequest.
type SigninRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Token expiration time in seconds
	ExpiresIn int `json:"expires_in"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// UserProfileResponse defines model for UserProfileResponse.
type UserProfileResponse struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
	Role  string              `json:"role"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Errors  []FieldError `json:"errors"`
	Message string       `json:"message"`
}

// BadRequest defines model for BadRequest.
type BadRequest = BadRequestError

// SignInUserJSONRequestBody defines body for SignInUser for application/json ContentType.
type SignInUserJSONRequestBody = SigninRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = SignupRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Sign in with email and password
	// (POST /auth/signin)
	SignInUser(c *gin.Context)
	// Register a new user
	// (POST /auth/signup)
	RegisterUser(c *gin.Context)
	// check server health
	// (GET /health)
	HealthCheck(c *gin.Context)
	// Get authenticated user profile
	// (GET /users/me)
	GetProfile(c *gin.Context)
	// Get user by ID
	// (GET /users/{id})
	GetUserById(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SignInUser operation middleware
func (siw *ServerInterfaceWrapper) SignInUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignInUser(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/signin", wrapper.SignInUser)
	router.POST(options.BaseURL+"/auth/signup", wrapper.RegisterUser)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
	router.GET(options.BaseURL+"/users/me", wrapper.GetProfile)
	router.GET(options.BaseURL+"/users/:id", wrapper.GetUserById)
}
